services:
  backend:
    build: .
    container_name: clarity-backend
    ports:
      - "80:8000"
    env_file: .env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - clarity-network

  redis:
    image: redis:alpine
    container_name: clarity-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - clarity-network

networks:
  clarity-network:
    driver: bridge
